### ISSUE TITLE
ValueError: loaded state dict has a different number of parameter groups

### ISSUE THREAD

**Issue by Melleaa** [feifeiobama/OrthogonalDet#8]
Dear author：
After I finish the task t1, I got this error :ValueError: loaded state dict has a different number of parameter groups.
I've tried your solution in #2 , changing the text model_final.pth to model_0019999.pth,but I still got this error.
I checked my log and found a warning:
fvcore.common.checkpoint WARNING: The checkpoint state_dict contains keys that are not used by the model:
  [35mstem.fc.{bias, weight}[0m
This occurred at the beginning of task1, I wonder if this impacts?
There were also warning when running task t2
Here's the total information:
```shell
[08/08 19:05:53 fvcore.common.checkpoint]: [Checkpointer] Loading from output/M-OWODB/model_0019999.pth ...
WARNING [08/08 19:05:54 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
head.head_series.0.calibration.0.{bias, weight}
head.head_series.1.calibration.0.{bias, weight}
head.head_series.2.calibration.0.{bias, weight}
head.head_series.3.calibration.0.{bias, weight}
head.head_series.4.calibration.0.{bias, weight}
head.head_series.5.calibration.0.{bias, weight}
[08/08 19:05:54 fvcore.common.checkpoint]: Loading trainer from output/M-OWODB/model_0019999.pth ...
[08/08 19:05:54 d2.engine.hooks]: Loading scheduler from state_dict ...
Traceback (most recent call last):
  File "train_net.py", line 281, in <module>
    launch(
  File "/raid/cjp/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_net.py", line 272, in main
    trainer.resume_or_load(resume=args.resume)
  File "/raid/cjp/detectron2/detectron2/engine/defaults.py", line 414, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
  File "/home/dl/anaconda3/envs/cjp/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 225, in resume_or_load
    return self.load(path)
  File "/raid/cjp/detectron2/detectron2/checkpoint/detection_checkpoint.py", line 62, in load
    ret = super().load(path, *args, **kwargs)
  File "/home/dl/anaconda3/envs/cjp/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 166, in load
    obj.load_state_dict(checkpoint.pop(key))
  File "/raid/cjp/detectron2/detectron2/engine/defaults.py", line 507, in load_state_dict
    self._trainer.load_state_dict(state_dict["_trainer"])
  File "/raid/cjp/detectron2/detectron2/engine/train_loop.py", line 430, in load_state_dict
    self.optimizer.load_state_dict(state_dict["optimizer"])
  File "/home/dl/anaconda3/envs/cjp/lib/python3.8/site-packages/torch/optim/optimizer.py", line 196, in load_state_dict
    raise ValueError("loaded state dict has a different number of "
ValueError: loaded state dict has a different number of parameter groups
``` 
/

**Comment by Melleaa** [comment]
Here's the total warning when I run t1,I wonder what's the question:
```shell
WARNING [08/08 20:59:59 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
alphas_cumprod
alphas_cumprod_prev
backbone.fpn_lateral2.{bias, weight}
backbone.fpn_lateral3.{bias, weight}
backbone.fpn_lateral4.{bias, weight}
backbone.fpn_lateral5.{bias, weight}
backbone.fpn_output2.{bias, weight}
backbone.fpn_output3.{bias, weight}
backbone.fpn_output4.{bias, weight}
backbone.fpn_output5.{bias, weight}
betas
head.head_series.0.bboxes_delta.{bias, weight}
head.head_series.0.class_logits.{bias, weight}
head.head_series.0.cls_module.0.weight
head.head_series.0.cls_module.1.{bias, weight}
head.head_series.0.inst_interact.dynamic_layer.{bias, weight}
head.head_series.0.inst_interact.norm1.{bias, weight}
head.head_series.0.inst_interact.norm2.{bias, weight}
head.head_series.0.inst_interact.norm3.{bias, weight}
head.head_series.0.inst_interact.out_layer.{bias, weight}
head.head_series.0.linear1.{bias, weight}
head.head_series.0.linear2.{bias, weight}
head.head_series.0.norm1.{bias, weight}
head.head_series.0.norm2.{bias, weight}
head.head_series.0.norm3.{bias, weight}
head.head_series.0.norm4.{bias, weight}
head.head_series.0.object_logit.{bias, running_mean, running_var, weight}
head.head_series.0.reg_module.0.weight
head.head_series.0.reg_module.1.{bias, weight}
head.head_series.0.reg_module.3.weight
head.head_series.0.reg_module.4.{bias, weight}
head.head_series.0.reg_module.6.weight
head.head_series.0.reg_module.7.{bias, weight}
head.head_series.0.self_attn.out_proj.{bias, weight}
head.head_series.0.self_attn.{in_proj_bias, in_proj_weight}
head.head_series.1.bboxes_delta.{bias, weight}
head.head_series.1.class_logits.{bias, weight}
head.head_series.1.cls_module.0.weight
head.head_series.1.cls_module.1.{bias, weight}
head.head_series.1.inst_interact.dynamic_layer.{bias, weight}
head.head_series.1.inst_interact.norm1.{bias, weight}
head.head_series.1.inst_interact.norm2.{bias, weight}
head.head_series.1.inst_interact.norm3.{bias, weight}
head.head_series.1.inst_interact.out_layer.{bias, weight}
head.head_series.1.linear1.{bias, weight}
head.head_series.1.linear2.{bias, weight}
head.head_series.1.norm1.{bias, weight}
head.head_series.1.norm2.{bias, weight}
head.head_series.1.norm3.{bias, weight}
head.head_series.1.norm4.{bias, weight}
head.head_series.1.object_logit.{bias, running_mean, running_var, weight}
head.head_series.1.reg_module.0.weight
head.head_series.1.reg_module.1.{bias, weight}
head.head_series.1.reg_module.3.weight
head.head_series.1.reg_module.4.{bias, weight}
head.head_series.1.reg_module.6.weight
head.head_series.1.reg_module.7.{bias, weight}
head.head_series.1.self_attn.out_proj.{bias, weight}
head.head_series.1.self_attn.{in_proj_bias, in_proj_weight}
head.head_series.2.bboxes_delta.{bias, weight}
head.head_series.2.class_logits.{bias, weight}
head.head_series.2.cls_module.0.weight
head.head_series.2.cls_module.1.{bias, weight}
head.head_series.2.inst_interact.dynamic_layer.{bias, weight}
head.head_series.2.inst_interact.norm1.{bias, weight}
head.head_series.2.inst_interact.norm2.{bias, weight}
head.head_series.2.inst_interact.norm3.{bias, weight}
head.head_series.2.inst_interact.out_layer.{bias, weight}
head.head_series.2.linear1.{bias, weight}
head.head_series.2.linear2.{bias, weight}
head.head_series.2.norm1.{bias, weight}
head.head_series.2.norm2.{bias, weight}
head.head_series.2.norm3.{bias, weight}
head.head_series.2.norm4.{bias, weight}
head.head_series.2.object_logit.{bias, running_mean, running_var, weight}
head.head_series.2.reg_module.0.weight
head.head_series.2.reg_module.1.{bias, weight}
head.head_series.2.reg_module.3.weight
head.head_series.2.reg_module.4.{bias, weight}
head.head_series.2.reg_module.6.weight
head.head_series.2.reg_module.7.{bias, weight}
head.head_series.2.self_attn.out_proj.{bias, weight}
head.head_series.2.self_attn.{in_proj_bias, in_proj_weight}
head.head_series.3.bboxes_delta.{bias, weight}
head.head_series.3.class_logits.{bias, weight}
head.head_series.3.cls_module.0.weight
head.head_series.3.cls_module.1.{bias, weight}
head.head_series.3.inst_interact.dynamic_layer.{bias, weight}
head.head_series.3.inst_interact.norm1.{bias, weight}
head.head_series.3.inst_interact.norm2.{bias, weight}
head.head_series.3.inst_interact.norm3.{bias, weight}
head.head_series.3.inst_interact.out_layer.{bias, weight}
head.head_series.3.linear1.{bias, weight}
head.head_series.3.linear2.{bias, weight}
head.head_series.3.norm1.{bias, weight}
head.head_series.3.norm2.{bias, weight}
head.head_series.3.norm3.{bias, weight}
head.head_series.3.norm4.{bias, weight}
head.head_series.3.object_logit.{bias, running_mean, running_var, weight}
head.head_series.3.reg_module.0.weight
head.head_series.3.reg_module.1.{bias, weight}
head.head_series.3.reg_module.3.weight
head.head_series.3.reg_module.4.{bias, weight}
head.head_series.3.reg_module.6.weight
head.head_series.3.reg_module.7.{bias, weight}
head.head_series.3.self_attn.out_proj.{bias, weight}
head.head_series.3.self_attn.{in_proj_bias, in_proj_weight}
head.head_series.4.bboxes_delta.{bias, weight}
head.head_series.4.class_logits.{bias, weight}
head.head_series.4.cls_module.0.weight
head.head_series.4.cls_module.1.{bias, weight}
head.head_series.4.inst_interact.dynamic_layer.{bias, weight}
head.head_series.4.inst_interact.norm1.{bias, weight}
head.head_series.4.inst_interact.norm2.{bias, weight}
head.head_series.4.inst_interact.norm3.{bias, weight}
head.head_series.4.inst_interact.out_layer.{bias, weight}
head.head_series.4.linear1.{bias, weight}
head.head_series.4.linear2.{bias, weight}
head.head_series.4.norm1.{bias, weight}
head.head_series.4.norm2.{bias, weight}
head.head_series.4.norm3.{bias, weight}
head.head_series.4.norm4.{bias, weight}
head.head_series.4.object_logit.{bias, running_mean, running_var, weight}
head.head_series.4.reg_module.0.weight
head.head_series.4.reg_module.1.{bias, weight}
head.head_series.4.reg_module.3.weight
head.head_series.4.reg_module.4.{bias, weight}
head.head_series.4.reg_module.6.weight
head.head_series.4.reg_module.7.{bias, weight}
head.head_series.4.self_attn.out_proj.{bias, weight}
head.head_series.4.self_attn.{in_proj_bias, in_proj_weight}
head.head_series.5.bboxes_delta.{bias, weight}
head.head_series.5.class_logits.{bias, weight}
head.head_series.5.cls_module.0.weight
head.head_series.5.cls_module.1.{bias, weight}
head.head_series.5.inst_interact.dynamic_layer.{bias, weight}
head.head_series.5.inst_interact.norm1.{bias, weight}
head.head_series.5.inst_interact.norm2.{bias, weight}
head.head_series.5.inst_interact.norm3.{bias, weight}
head.head_series.5.inst_interact.out_layer.{bias, weight}
head.head_series.5.linear1.{bias, weight}
head.head_series.5.linear2.{bias, weight}
head.head_series.5.norm1.{bias, weight}
head.head_series.5.norm2.{bias, weight}
head.head_series.5.norm3.{bias, weight}
head.head_series.5.norm4.{bias, weight}
head.head_series.5.object_logit.{bias, running_mean, running_var, weight}
head.head_series.5.reg_module.0.weight
head.head_series.5.reg_module.1.{bias, weight}
head.head_series.5.reg_module.3.weight
head.head_series.5.reg_module.4.{bias, weight}
head.head_series.5.reg_module.6.weight
head.head_series.5.reg_module.7.{bias, weight}
head.head_series.5.self_attn.out_proj.{bias, weight}
head.head_series.5.self_attn.{in_proj_bias, in_proj_weight}
log_one_minus_alphas_cumprod
posterior_log_variance_clipped
posterior_mean_coef1
posterior_mean_coef2
posterior_variance
sqrt_alphas_cumprod
sqrt_one_minus_alphas_cumprod
sqrt_recip_alphas_cumprod
sqrt_recipm1_alphas_cumprod
WARNING [08/08 20:59:59 fvcore.common.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  stem.fc.{bias, weight}
```

**Comment by feifeiobama** [comment]
I've checked my log and found the same warning, so I think the error is likely caused by something else. Meanwhile, please try deleting the current checkpoint folder and re-running the experiments for Task 1 and Task 2.

**Comment by Melleaa** [comment]
Thank you for your reply! But I want to clarify if you mean deleting the output folder and then retrying? I have already tried that, and it didn't work. Or do you mean deleting the last_checkpoint file? Or should I delete the contents inside last_checkpoint?

**Comment by feifeiobama** [comment]
I meant deleting the output folder and then retrying. If that doesn't work, maybe you can download a checkpoint from the provided [link](https://drive.google.com/drive/folders/1XTTmjC_oVA2-J8l-bBdBo9nrQVq-lgKm) and modify the last_checkpoint file to specify that checkpoint for resuming.

**Comment by Melleaa** [comment]
OK! Thank you! I'll try.

**Comment by amajee11us** [comment]
Hi @feifeiobama I have tried all the steps as discussed in this issue and also https://github.com/feifeiobama/OrthogonalDet/issues/2 but the issue continues to persist. I think there is some inconsistency in the configuration with which you are running your model vs the code on the repository. Can you please verify that and provide a solution ?
Using pretrained checkpoints for a continued task (I mean from t1 --> t2 --> etc.) is not a solution but seems like a hack.

**Comment by feifeiobama** [comment]
> Hi [@feifeiobama](https://github.com/feifeiobama) I have tried all the steps as discussed in this issue and also [#2](https://github.com/feifeiobama/OrthogonalDet/issues/2) but the issue continues to persist. I think there is some inconsistency in the configuration with which you are running your model vs the code on the repository. Can you please verify that and provide a solution ? Using pretrained checkpoints for a continued task (I mean from t1 --> t2 --> etc.) is not a solution but seems like a hack.

Thank you for the suggestion. Given that these configurations are exactly the ones I used, I suspect that there may be some environemntal differences, e.g. in pytorch and detectron2 versions. But for now, I don’t have the resource (e.g. data, cluster) or time to further verify it. Perhaps you can start with configuring the environment using earlier package versions (roughly the deadline of cvpr24).

**Comment by zhanghuazhong0318** [comment]
> > Hi [@feifeiobama](https://github.com/feifeiobama) I have tried all the steps as discussed in this issue and also [#2](https://github.com/feifeiobama/OrthogonalDet/issues/2) but the issue continues to persist. I think there is some inconsistency in the configuration with which you are running your model vs the code on the repository. Can you please verify that and provide a solution ? Using pretrained checkpoints for a continued task (I mean from t1 --> t2 --> etc.) is not a solution but seems like a hack.
> 
> Thank you for the suggestion. Given that these configurations are exactly the ones I used, I suspect that there may be some environemntal differences, e.g. in pytorch and detectron2 versions. But for now, I don’t have the resource (e.g. data, cluster) or time to further verify it. Perhaps you can start with configuring the environment using earlier package versions (roughly the deadline of cvpr24).

Hi @feifeiobama I got the same 'loaded state dict' ValueError as #2  mentioned, can you please share the environmental  versions you used？ I want to take that as a reference. Thanks!

**Comment by PickyPie** [comment]
> > Hi [@feifeiobama](https://github.com/feifeiobama) I have tried all the steps as discussed in this issue and also [#2](https://github.com/feifeiobama/OrthogonalDet/issues/2) but the issue continues to persist. I think there is some inconsistency in the configuration with which you are running your model vs the code on the repository. Can you please verify that and provide a solution ? Using pretrained checkpoints for a continued task (I mean from t1 --> t2 --> etc.) is not a solution but seems like a hack.
> 
> Thank you for the suggestion. Given that these configurations are exactly the ones I used, I suspect that there may be some environemntal differences, e.g. in pytorch and detectron2 versions. But for now, I don’t have the resource (e.g. data, cluster) or time to further verify it. Perhaps you can start with configuring the environment using earlier package versions (roughly the deadline of cvpr24).

Dear author[@feifeiobama](https://github.com/feifeiobama), like others, I have encountered the same problem.
My attempted solution was to remove the --resume parameter and start training from scratch at each new stage (e.g., t2_ft → t3, t3_ft → t4).
However, I am not sure whether this affects the training results.
My final reproduced performance is indeed worse than that reported in the original paper, especially the abnormally high recall of unknown classes at the t2 stage.
The evaluation logs are attached below:
T1 阶段
Known AP50: 62.54%
Unknown Recall50: 21.49%
WI (Wilderness Impact): 0.0393 (取0.7阈值)
AOSE: 4404
T2 阶段
Known AP50: 47.20%
Unknown Recall50: 40.85%
WI (Wilderness Impact): 0.0150 (取0.7阈值)
AOSE: 1379
T3 阶段
Known AP50: 39.55%
Unknown Recall50: 20.77%
WI (Wilderness Impact): 0.0091 (取0.7阈值)
AOSE: 1042
T4 阶段
Known AP50: 35.22%
Unknown Recall50: NaN
